name: Push Changes to Another Repository

on:
  push:
    branches:
      - main 

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - run: pnpm install

  deploy:
    runs-on: ubuntu-latest

    needs: install

    steps:
      - uses: actions/checkout@v3
        with:
          repository: GeeksForGeeksSRMIST/gfgsrm-website-deploy
          persist-credentials: true

      - run: pnpm install

      - run: git config user.name "GitHub Actions"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: git config user.email "github-actions@users.noreply.github.com"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: git checkout -b deploy-changes

      - run: git pull origin master

      - run: git merge origin/main

      - run: git push origin deploy-changes
