name: Push to Another Repository

on:
  push:
    branches:
      - main

jobs:
  push-to-another-repository:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Configure SSH Key
        uses: actions/setup-ssh@v2
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-private-key-passphrase: ${{ secrets.SSH_PRIVATE_KEY_PASSPHRASE }}
          ssh-key-name: "pushtogfgdeployment"
      - name: Add Another Repository
        run: |
          git remote add another-repo git@github.com:GeeksForGeeksSRMIST/gfgsrm-website-deploy.git
      - name: Push to Another Repository
        run: git push another-repo ${{ github.ref }}
